/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalisesRouteImport } from './routes/_authenticated/analises'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedComparativosRouteImport } from './routes/_authenticated/comparativos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartamentosRouteImport } from './routes/_authenticated/departamentos'
import { Route as AuthenticatedEquipesRouteImport } from './routes/_authenticated/equipes'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedPlanosDeAcaoRouteImport } from './routes/_authenticated/planos-de-acao'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AuthenticatedResultadosRouteImport } from './routes/_authenticated/resultados'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalisesRoute = AuthenticatedAnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComparativosRoute =
  AuthenticatedComparativosRouteImport.update({
    id: '/comparativos',
    path: '/comparativos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartamentosRoute =
  AuthenticatedDepartamentosRouteImport.update({
    id: '/departamentos',
    path: '/departamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipesRoute = AuthenticatedEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosDeAcaoRoute =
  AuthenticatedPlanosDeAcaoRouteImport.update({
    id: '/planos-de-acao',
    path: '/planos-de-acao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultadosRoute = AuthenticatedResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analises': typeof AuthenticatedAnalisesRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/comparativos': typeof AuthenticatedComparativosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departamentos': typeof AuthenticatedDepartamentosRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/planos-de-acao': typeof AuthenticatedPlanosDeAcaoRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/resultados': typeof AuthenticatedResultadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analises': typeof AuthenticatedAnalisesRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/comparativos': typeof AuthenticatedComparativosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departamentos': typeof AuthenticatedDepartamentosRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/planos-de-acao': typeof AuthenticatedPlanosDeAcaoRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/resultados': typeof AuthenticatedResultadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analises': typeof AuthenticatedAnalisesRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/comparativos': typeof AuthenticatedComparativosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departamentos': typeof AuthenticatedDepartamentosRoute
  '/_authenticated/equipes': typeof AuthenticatedEquipesRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/planos-de-acao': typeof AuthenticatedPlanosDeAcaoRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/_authenticated/resultados': typeof AuthenticatedResultadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analises'
    | '/colaboradores'
    | '/comparativos'
    | '/dashboard'
    | '/departamentos'
    | '/equipes'
    | '/indicadores'
    | '/metas'
    | '/planos-de-acao'
    | '/rankings'
    | '/resultados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analises'
    | '/colaboradores'
    | '/comparativos'
    | '/dashboard'
    | '/departamentos'
    | '/equipes'
    | '/indicadores'
    | '/metas'
    | '/planos-de-acao'
    | '/rankings'
    | '/resultados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analises'
    | '/_authenticated/colaboradores'
    | '/_authenticated/comparativos'
    | '/_authenticated/dashboard'
    | '/_authenticated/departamentos'
    | '/_authenticated/equipes'
    | '/_authenticated/indicadores'
    | '/_authenticated/metas'
    | '/_authenticated/planos-de-acao'
    | '/_authenticated/rankings'
    | '/_authenticated/resultados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analises': {
      id: '/_authenticated/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AuthenticatedAnalisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparativos': {
      id: '/_authenticated/comparativos'
      path: '/comparativos'
      fullPath: '/comparativos'
      preLoaderRoute: typeof AuthenticatedComparativosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departamentos': {
      id: '/_authenticated/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof AuthenticatedDepartamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipes': {
      id: '/_authenticated/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AuthenticatedEquipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos-de-acao': {
      id: '/_authenticated/planos-de-acao'
      path: '/planos-de-acao'
      fullPath: '/planos-de-acao'
      preLoaderRoute: typeof AuthenticatedPlanosDeAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resultados': {
      id: '/_authenticated/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof AuthenticatedResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalisesRoute: typeof AuthenticatedAnalisesRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedComparativosRoute: typeof AuthenticatedComparativosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartamentosRoute: typeof AuthenticatedDepartamentosRoute
  AuthenticatedEquipesRoute: typeof AuthenticatedEquipesRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPlanosDeAcaoRoute: typeof AuthenticatedPlanosDeAcaoRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedResultadosRoute: typeof AuthenticatedResultadosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalisesRoute: AuthenticatedAnalisesRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedComparativosRoute: AuthenticatedComparativosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartamentosRoute: AuthenticatedDepartamentosRoute,
  AuthenticatedEquipesRoute: AuthenticatedEquipesRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPlanosDeAcaoRoute: AuthenticatedPlanosDeAcaoRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedResultadosRoute: AuthenticatedResultadosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
